sonar-project.properties


sonar.projectKey=zaman-mimari-app
sonar.projectName=Zaman Mimari
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=js
sonar.sourceEncoding=UTF-8

# BU SATIRI EKLE: Local sunucu adresin (Varsayılan 9000'dir)
sonar.host.url=http://localhost:9000

# Gereksiz dosyaları tarama dışı bırak
sonar.exclusions=node_modules/**, .next/**, out/**, public/**